<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textArea</name>
   <tag></tag>
   <elementGuidId>b7fceab3-f5af-4e2e-8e33-0b08879524b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//textarea[@id='ctl00_ContentPlaceholder1_RadTextBox3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//textarea[@id='ctl00_ContentPlaceholder1_RadTextBox3']</value>
   </webElementProperties>
</WebElementEntity>
